// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBUiuITIqoTjhhIKaUfyvzaGgqREvMoGow',
    appId: '1:490930402290:web:f0bd3c6234de7b6983716b',
    messagingSenderId: '490930402290',
    projectId: 'snake-1fdc7',
    authDomain: 'snake-1fdc7.firebaseapp.com',
    storageBucket: 'snake-1fdc7.appspot.com',
    measurementId: 'G-VVWNWRSZ07',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB2JD-oNWsrGAGciAhTQHv1rkG0e8B73tQ',
    appId: '1:490930402290:android:946419e0215e06a283716b',
    messagingSenderId: '490930402290',
    projectId: 'snake-1fdc7',
    storageBucket: 'snake-1fdc7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCzzQCpv4mFmXshZMukGoGHRU4qIbRXjvo',
    appId: '1:490930402290:ios:e3a9a98a459930f883716b',
    messagingSenderId: '490930402290',
    projectId: 'snake-1fdc7',
    storageBucket: 'snake-1fdc7.appspot.com',
    iosClientId: '490930402290-d3fv6fqhvlp83tl5rvi05r392sl0r2ln.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCzzQCpv4mFmXshZMukGoGHRU4qIbRXjvo',
    appId: '1:490930402290:ios:e3a9a98a459930f883716b',
    messagingSenderId: '490930402290',
    projectId: 'snake-1fdc7',
    storageBucket: 'snake-1fdc7.appspot.com',
    iosClientId: '490930402290-d3fv6fqhvlp83tl5rvi05r392sl0r2ln.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication',
  );
}
